In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/reviews.csv")

In [4]:
df.head()

,Professor_ID,Professor_Name,University,Department,Quality,Difficulty,Class_Name,Comment,Thumbs_Up,Thumbs_Down,Review_Date
0,2099061,Katherine Maurer,Acad department,Acad department,1.0,4.0,SWRK635,Avoid! Takes 2 months to grade assignments so ...,0.0,0.0,"Nov 18th, 2024"
1,21522,Ralph Cecere,Accounting department,Accounting department,3.0,3.0,ACCT351,"Ralph is very nice guy, more than happy to cha...",0.0,0.0,"Nov 13th, 2025"
2,21522,Ralph Cecere,Accounting department,Accounting department,1.0,4.0,ACCT351,"His lecture structure is really unclear, which...",0.0,0.0,"Jul 24th, 2025"
3,21522,Ralph Cecere,Accounting department,Accounting department,1.0,4.0,ACCT351,Avoid at all costs. The material from his slid...,0.0,0.0,"May 11th, 2025"
4,21522,Ralph Cecere,Accounting department,Accounting department,1.0,4.0,ACCT475,Worst prof of my undergraduate. You can't avoi...,0.0,0.0,"May 8th, 2025"

In [5]:
def transform_data(df: pd.DataFrame):
    prof_name = df["Professor_Name"]
    review = df["Comment"]
    department = df["Department"]
    
    return f"{prof_name}: {department} : {review}"

In [6]:
df = df.apply(transform_data, axis=1)
df = pd.DataFrame(df)

In [7]:
df.to_csv("../data/data.csv", index=False)

In [14]:
df

                                                       0
0      Katherine Maurer: Acad department : Avoid! Tak...
1      Ralph Cecere: Accounting department : Ralph is...
2      Ralph Cecere: Accounting department : His lect...
3      Ralph Cecere: Accounting department : Avoid at...
4      Ralph Cecere: Accounting department : Worst pr...
...                                                  ...
58244  Sarah Wolfson: Writing department : BEST PROF ...
58245  Sarah Wolfson: Writing department : Best teach...
58246  Sarah Wolfson: Writing department : Her class ...
58247  Sarah Wolfson: Writing department : She is the...
58248  Sarah Wolfson: Writing department : A nice and...

[58249 rows x 1 columns]